"""add_email_password

Revision ID: 0052fae7185c
Revises: a1df55a54d8b
Create Date: 2018-09-22 21:06:40.874362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0052fae7185c'
down_revision = 'a1df55a54d8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('author', sa.Column('email', sa.String(length=128), nullable=True))
    op.add_column('author', sa.Column('password', sa.Integer(), nullable=True))
    op.create_unique_constraint(None, 'author', ['password'])
    op.create_unique_constraint(None, 'author', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('password', 'author', type_='unique')
    op.drop_constraint('email', 'author', type_='unique')
    op.drop_column('author', 'password')
    op.drop_column('author', 'email')
    # ### end Alembic commands ###
